const countries = [
    { label: "Essuatíni", value: "Essuatíni" },
    { label: "Índia", value: "Índia" },
    { label: "Maláui", value: "Maláui" },
    { label: "Portugal", value: "Portugal" },
    { label: "Tanzânia", value: "Tanzânia" },
    { label: "Zâmbia", value: "Zâmbia" },
    { label: "Zimbábue", value: "Zimbábue" },
    { label: "África do Sul", value: "África do Sul" },
  
    { label: "Afeganistão", value: "Afeganistão" },
    { label: "Albânia", value: "Albânia" },
    { label: "Alemanha", value: "Alemanha" },
  
    { label: "Andorra", value: "Andorra" },
    { label: "Angola", value: "Angola" },
    { label: "Antiga e Barbuda", value: "Antiga e Barbuda" },
  
    { label: "Arábia Saudita", value: "Arábia Saudita" },
    { label: "Argélia", value: "Argélia" },
    { label: "Argentina", value: "Argentina" },
    { label: "Arménia", value: "Arménia" },
    { label: "Austrália", value: "Austrália" },
    { label: "Áustria", value: "Áustria" },
    { label: "Azerbaijão", value: "Azerbaijão" },
    { label: "Bahamas", value: "Bahamas" },
    { label: "Bangladexe", value: "Bangladexe" },
    { label: "Barbados", value: "Barbados" },
    { label: "Barém", value: "Barém" },
    { label: "Bélgica", value: "Bélgica" },
    { label: "Belize", value: "Belize" },
    { label: "Benim", value: "Benim" },
    { label: "Bielorrússia", value: "Bielorrússia" },
    { label: "Bolívia", value: "Bolívia" },
    { label: "Bósnia e Herzegovina", value: "Bósnia e Herzegovina" },
    { label: "Botsuana", value: "Botsuana" },
    { label: "Brasil", value: "Brasil" },
    { label: "Brunei", value: "Brunei" },
    { label: "Bulgária", value: "Bulgária" },
  
    { label: "Burquina Faso", value: "Burquina Faso" },
    { label: "Burúndi", value: "Burúndi" },
    { label: "Butão", value: "Butão" },
    { label: "Cabo Verde", value: "Cabo Verde" },
    { label: "Camarões", value: "Camarões" },
    { label: "Camboja", value: "Camboja" },
    { label: "Canadá", value: "Canadá" },
    { label: "Catar", value: "Catar" },
    { label: "Cazaquistão", value: "Cazaquistão" },
    { label: "Chade", value: "Chade" },
    { label: "Chile", value: "Chile" },
    { label: "China", value: "China" },
    { label: "Chipre", value: "Chipre" },
    { label: "Colômbia", value: "Colômbia" },
    { label: "Comores", value: "Comores" },
    { label: "Congo-Brazzaville", value: "Congo-Brazzaville" },
    { label: "Coreia do Norte", value: "Coreia do Norte" },
    { label: "Coreia do Sul", value: "Coreia do Sul" },
    { label: "Costa do Marfim", value: "Costa do Marfim" },
    { label: "Costa Rica", value: "Costa Rica" },
    { label: "Croácia", value: "Croácia" },
    { label: "Cuba", value: "Cuba" },
    { label: "Dinamarca", value: "Dinamarca" },
    { label: "Dominica", value: "Dominica" },
    { label: "Egito", value: "Egito" },
    { label: "Emirados Árabes Unidos", value: "Emirados Árabes Unidos" },
    { label: "Equador", value: "Equador" },
    { label: "Eritreia", value: "Eritreia" },
    { label: "Eslováquia", value: "Eslováquia" },
    { label: "Eslovénia", value: "Eslovénia" },
    { label: "Espanha", value: "Espanha" },
    { label: "Estado da Palestina", value: "Estado da Palestina" },
    { label: "Estados Unidos de América", value: "Estados Unidos de América" },
    { label: "Estónia", value: "Estónia" },
    { label: "Etiópia", value: "Etiópia" },
    { label: "Fiji", value: "Fiji" },
    { label: "Filipinas", value: "Filipinas" },
    { label: "Finlândia", value: "Finlândia" },
    { label: "França", value: "França" },
    { label: "Gabão", value: "Gabão" },
    { label: "Gâmbia", value: "Gâmbia" },
    { label: "Gana", value: "Gana" },
    { label: "Geórgia", value: "Geórgia" },
    { label: "Granada", value: "Granada" },
    { label: "Grécia", value: "Grécia" },
    { label: "Guatemala", value: "Guatemala" },
    { label: "Guiana", value: "Guiana" },
    { label: "Guiné", value: "Guiné" },
    { label: "Guiné Equatorial", value: "Guiné Equatorial" },
    { label: "Guiné-Bissau", value: "Guiné-Bissau" },
    { label: "Haiti", value: "Haiti" },
    { label: "Honduras", value: "Honduras" },
    { label: "Hungria", value: "Hungria" },
    { label: "Iémen", value: "Iémen" },
    { label: "Ilhas Marechal", value: "Ilhas Marechal" },
    { label: "Indonésia", value: "Indonésia" },
    { label: "Irão", value: "Irão" },
    { label: "Iraque", value: "Iraque" },
    { label: "Irlanda", value: "Irlanda" },
    { label: "Islândia", value: "Islândia" },
    { label: "Israel", value: "Israel" },
    { label: "Itália", value: "Itália" },
    { label: "Jamaica", value: "Jamaica" },
    { label: "Japão", value: "Japão" },
    { label: "Jibuti", value: "Jibuti" },
    { label: "Jordânia", value: "Jordânia" },
    { label: "Laus", value: "Laus" },
    { label: "Lesoto", value: "Lesoto" },
    { label: "Letónia", value: "Letónia" },
    { label: "Líbano", value: "Líbano" },
    { label: "Libéria", value: "Libéria" },
    { label: "Líbia", value: "Líbia" },
    { label: "Listenstaine", value: "Listenstaine" },
    { label: "Lituânia", value: "Lituânia" },
    { label: "Luxemburgo", value: "Luxemburgo" },
    { label: "Macedónia do Norte", value: "Macedónia do Norte" },
    { label: "Madagáscar", value: "Madagáscar" },
    { label: "Malásia", value: "Malásia" },
    { label: "Maldivas", value: "Maldivas" },
    { label: "Mali", value: "Mali" },
    { label: "Malta", value: "Malta" },
    { label: "Marrocos", value: "Marrocos" },
    { label: "Maurícia", value: "Maurícia" },
    { label: "Mauritânia", value: "Mauritânia" },
    { label: "México", value: "México" },
    { label: "Mianmar", value: "Mianmar" },
    { label: "Micronésia", value: "Micronésia" },
    { label: "Moçambique", value: "Moçambique" },
    { label: "Moldávia", value: "Moldávia" },
    { label: "Mónaco", value: "Mónaco" },
    { label: "Mongólia", value: "Mongólia" },
    { label: "Montenegro", value: "Montenegro" },
    { label: "Namíbia", value: "Namíbia" },
    { label: "Nauru", value: "Nauru" },
    { label: "Nepal", value: "Nepal" },
    { label: "Nicarágua", value: "Nicarágua" },
    { label: "Níger", value: "Níger" },
    { label: "Nigéria", value: "Nigéria" },
    { label: "Noruega", value: "Noruega" },
    { label: "Nova Zelândia", value: "Nova Zelândia" },
    { label: "Omã", value: "Omã" },
    { label: "Países Baixos", value: "Países Baixos" },
    { label: "Palau", value: "Palau" },
    { label: "Panamá", value: "Panamá" },
    { label: "Papua Nova Guiné", value: "Papua Nova Guiné" },
    { label: "Paquistão", value: "Paquistão" },
    { label: "Paraguai", value: "Paraguai" },
    { label: "Peru", value: "Peru" },
    { label: "Polónia", value: "Polónia" },
    { label: "Quénia", value: "Quénia" },
    { label: "Quirguistão", value: "Quirguistão" },
    { label: "Quiribáti", value: "Quiribáti" },
    { label: "Reino Unido", value: "Reino Unido" },
    { label: "República Centro-Africana", value: "República Centro-Africana" },
    { label: "República Checa", value: "República Checa" },
    {
      label: "República Democrática do Congo",
      value: "República Democrática do Congo",
    },
    { label: "República Dominicana", value: "República Dominicana" },
    { label: "Roménia", value: "Roménia" },
    { label: "Ruanda", value: "Ruanda" },
    { label: "Rússia", value: "Rússia" },
    { label: "Salomão", value: "Salomão" },
    { label: "Salvador", value: "Salvador" },
    { label: "Samoa", value: "Samoa" },
    { label: "Santa Lúcia", value: "Santa Lúcia" },
    { label: "São Cristóvão e Neves", value: "São Cristóvão e Neves" },
    { label: "São Marinho", value: "São Marinho" },
    { label: "São Tomé e Príncipe", value: "São Tomé e Príncipe" },
    { label: "São Vicente e Granadinas", value: "São Vicente e Granadinas" },
    { label: "Seicheles", value: "Seicheles" },
    { label: "Senegal", value: "Senegal" },
    { label: "Serra Leoa", value: "Serra Leoa" },
    { label: "Sérvia", value: "Sérvia" },
    { label: "Singapura", value: "Singapura" },
    { label: "Síria", value: "Síria" },
    { label: "Somália", value: "Somália" },
    { label: "Sri Lanca", value: "Sri Lanca" },
    { label: "Sudão", value: "Sudão" },
    { label: "Sudão do Sul", value: "Sudão do Sul" },
    { label: "Suécia", value: "Suécia" },
    { label: "Suíça", value: "Suíça" },
    { label: "Suriname", value: "Suriname" },
    { label: "Tailândia", value: "Tailândia" },
    { label: "Taiuã", value: "Taiuã" },
    { label: "Tajiquistão", value: "Tajiquistão" },
    { label: "Timor-Leste", value: "Timor-Leste" },
    { label: "Togo", value: "Togo" },
    { label: "Tonga", value: "Tonga" },
    { label: "Trindade e Tobago", value: "Trindade e Tobago" },
    { label: "Tunísia", value: "Tunísia" },
    { label: "Turcomenistão", value: "Turcomenistão" },
    { label: "Turquia", value: "Turquia" },
  
    { label: "Tuvalu", value: "Tuvalu" },
    { label: "Ucrânia", value: "Ucrânia" },
    { label: "Uganda", value: "Uganda" },
    { label: "Uruguai", value: "Uruguai" },
    { label: "Usbequistão", value: "Usbequistão" },
    { label: "Vanuatu", value: "Vanuatu" },
    { label: "Vaticano", value: "Vaticano" },
    { label: "Venezuela", value: "Venezuela" },
    { label: "Vietname", value: "Vietname" },
  ];
  export default countries;
  